name: Deployment

on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Config vcpkg
      run: |
        vcpkg integrate install
      
    - name: Install dependencies
      continue-on-error: true
      run: |
        msbuild -p:Configuration=Release -p:Platform=x86 -restore -m
        
    - name: Build the solution
      run: |
        msbuild -p:Configuration=Release -p:Platform=x86 -restore -m
        
    - name: Delete unnecessary files
      run: |
        cd Release
        del *.exp -Force
        del *.lib -Force
        del *.pdb -Force
        del de -Recurse -Force
        cd ..
        
    - name: List built files
      run: |
        cd Release
        ls
        cd ..